general:
  mode: "train"
  seed: null
  ckpt_path: saved/Train_Carla_New/last.ckpt
  project_name: mask4former
  instance_population: 20
  dbscan_eps: null
  experiment_name: ${now:%Y-%m-%d_%H%M%S}
  save_dir: saved/${general.experiment_name}
  gpus: 1

defaults:
  - _self_
  - data: carla
  - data/data_loaders: simple_loader
  - data/datasets: semantic-carla
  - data/collation_functions: voxelize_collate
  - logging: full
  - model: mask4former
  - optimizer: adamw
  - scheduler: onecyclelr
  - trainer: trainer30
  - callbacks: callbacks_panoptic
  - loss: set_criterion
  - metric: pq

hydra:
  run:
    dir: saved/hydra_logs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: saved/hydra_logs/${now:%Y-%m-%d}/${now:%H-%M-%S}
    # dir: ${general.save_dir}
    subdir: ${hydra.job.num}_${hydra.job.id}
